import type { Analysis } from "@/lib/schema";

/**
 * Pre-cached analyses for seeded enquiries.
 *
 * Generated by scripts/precache-seeds.ts. Re-run after editing the prompt
 * or sample enquiries: `npm run cache-seeds`.
 *
 * The dashboard renders these instantly on click; only user-pasted
 * enquiries hit Gemini live. Documented in README "Why we pre-cache".
 */
export const seededAnalyses: Record<string, Analysis> = {
  "enq-001": {
    "classification": "seller_enquiry",
    "classification_confidence": 0.98,
    "classification_reasoning": "Owner of a strata management business explicitly stating intent to 'plan my exit' and asking about the 'process' and 'multipliers'.",
    "urgency": "medium",
    "geography": "NSW",
    "route_to": "senior_broker",
    "recommended_action": "Acknowledge the exit plan and address initial questions regarding process, multipliers, and confidentiality. Offer a discovery call.",
    "suggested_reply": {
      "subject": "Re: Your enquiry regarding selling Whitman Strata Pty Ltd",
      "body": "Hi Sarah,\n\nThanks for reaching out. We understand you're looking to plan your exit from Whitman Strata Pty Ltd over the next 18 months, and we regularly assist owners of businesses of your size in Sydney.\n\nWe can certainly walk you through our sale process, provide insights into current market multipliers, and explain how we ensure confidentiality with staff and clients throughout. We have indeed facilitated sales of similar-sized portfolios in NSW recently.\n\nWould you be available for a brief introductory call sometime during a weekday morning next week? We can then discuss your specific situation and objectives in more detail.\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": []
  },
  "enq-002": {
    "classification": "buyer_enquiry",
    "classification_confidence": 0.98,
    "classification_reasoning": "Private Equity fund with committed capital and clear acquisition criteria for strata management businesses.",
    "urgency": "high",
    "geography": "NSW",
    "route_to": "principal",
    "recommended_action": "Principal to respond directly to arrange an introductory call to discuss market opportunities for their roll-up strategy.",
    "suggested_reply": {
      "subject": "Re: Strata Management Roll-up Opportunity - Atlas Private Capital",
      "body": "Good morning Marcus,\n\nThanks for reaching out from Atlas Private Capital. We regularly work with private equity firms entering or expanding in the strata management vertical, and understand your interest in the NSW and VIC markets.\n\nYour target acquisition range and stated ability to move quickly align well with the types of opportunities we often represent.\n\nOur principal broker, [Principal's Name], would be best placed to have an introductory discussion. Would you be available for a brief call next week to explore what might be suitable for your next fund cycle?\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": [
      "high_value_lead"
    ]
  },
  "enq-003": {
    "classification": "buyer_enquiry",
    "classification_confidence": 0.95,
    "classification_reasoning": "Existing operator with stated portfolio size, geography, acquisition criteria, and timeframe.",
    "urgency": "high",
    "geography": "QLD",
    "route_to": "senior_broker",
    "recommended_action": "Reply within 24 hours; offer NDA and an initial buyer-criteria call. Add to active buy-side list for SE QLD opportunities.",
    "suggested_reply": {
      "subject": "Re: SE QLD acquisition opportunities",
      "body": "Hi Helen,\n\nThanks for reaching out again. We appreciate Capital Strata Group's continued interest in expanding within South East QLD.\n\nWe are actively working with several operators in your target region who are exploring exits and would be happy to discuss what may be a suitable fit for your 1,000–3,000 lot acquisition criteria.\n\nI'll send through our standard mutual NDA shortly. Once that's in place, we can arrange a brief call to walk through your specific requirements in more detail and review any relevant active opportunities.\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": []
  },
  "enq-004": {
    "classification": "seller_enquiry",
    "classification_confidence": 0.35,
    "classification_reasoning": "Mentions \"selling\" but provides no portfolio, geography, or context.",
    "urgency": "low",
    "geography": "unspecified",
    "route_to": "intake",
    "recommended_action": "Reply with three qualifying questions before booking a call: portfolio size, geography, and timeline.",
    "suggested_reply": {
      "subject": "Re: your enquiry",
      "body": "Hi,\n\nThanks for reaching out. So we can prepare for a useful call, would you mind sharing a few quick details:\n\n1. Approximately how many lots does your business currently manage?\n2. Which state or region is the portfolio concentrated in?\n3. Roughly what timeline are you considering for an exit?\n\nOnce we have those, we can get a meaningful conversation organised quickly.\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": [
      "vague_input",
      "needs_clarification"
    ]
  },
  "enq-005": {
    "classification": "general_question",
    "classification_confidence": 0.98,
    "classification_reasoning": "The user wants to sell a residential apartment, which is outside our domain of brokering strata management businesses.",
    "urgency": "low",
    "geography": "NSW",
    "route_to": "intake",
    "recommended_action": "Reply with polite redirect clarifying our specialisation and advising them to contact a residential real estate agent.",
    "suggested_reply": {
      "subject": "Re: Your enquiry about selling an apartment",
      "body": "Hi Tom,\n\nThanks for getting in touch. To clarify – Strata Business Brokers specialises in the sale and purchase of strata management businesses (the agencies that manage apartment buildings), not individual residential properties or apartments.\n\nFor selling your 2-bedroom apartment in North Bondi, you'll need to contact a residential real estate agent. They will be best placed to advise on listing fees and marketing strategies for your property.\n\nWe wish you the best of luck with your sale.\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": [
      "out_of_scope"
    ]
  },
  "enq-006": {
    "classification": "seller_enquiry",
    "classification_confidence": 0.97,
    "classification_reasoning": "Founder of a 4,500-lot NSW agency exploring sale with explicit confidentiality requirement.",
    "urgency": "high",
    "geography": "NSW",
    "route_to": "principal",
    "recommended_action": "Principal-level handling. Acknowledge confidentiality, outline the CIM and exclusive engagement process, respecting the 'email only' preference. Request preferred private contact channel before any further detail.",
    "suggested_reply": {
      "subject": "Re: your enquiry — confidential",
      "body": "Good afternoon Daniel,\n\nThank you for reaching out, and your concern about discretion is well placed — confidentiality is the most common requirement in our seller engagements and we have an established process for it.\n\nIn short: we use a coded Confidential Information Memorandum (CIM) that does not name your business, and we only release identifying detail after qualified buyers have signed both an NDA and our exclusivity engagement. Staff and client awareness is managed by limiting all communications to a private channel of your choosing, such as email as you've requested.\n\nI'd suggest we arrange a brief 20-minute introductory call with our principal broker. Please let us know a suitable time and a private mobile number, and we will organise that for you.\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": [
      "confidentiality_required",
      "high_value_lead"
    ]
  },
  "enq-007": {
    "classification": "referral_partner",
    "classification_confidence": 0.98,
    "classification_reasoning": "Chartered Accountant is referring a client who owns a strata management business and is ready to explore a sale.",
    "urgency": "high",
    "geography": "VIC",
    "route_to": "partner_referral",
    "recommended_action": "Schedule a call with the referring accountant to vet the brokerage and outline the seller engagement process for their client.",
    "suggested_reply": {
      "subject": "Re: Strata Management Business Sale Referral - VIC",
      "body": "Hi Priya,\n\nThanks for reaching out and for considering Strata Business Brokers for your client's strata management business sale. We'd be delighted to assist.\n\nWe understand your client is exploring an exit as part of their retirement planning for their 1,800-lot portfolio in Victoria, and vetting our services is a sensible first step.\n\nI would be pleased to schedule a brief call this week to introduce our approach, explain our process for sellers, and address any questions you or your client might have. Please let me know what day and time works best for you.\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": []
  },
  "enq-008": {
    "classification": "general_question",
    "classification_confidence": 0.9,
    "classification_reasoning": "The enquiry asks about the brokerage's fee structure and typical engagement length.",
    "urgency": "low",
    "geography": "unspecified",
    "route_to": "intake",
    "recommended_action": "Provide a brief overview of the fee structure (typically success-based percentage) and engagement length; invite a follow-up call to discuss specific scenarios.",
    "suggested_reply": {
      "subject": "Re: Your enquiry",
      "body": "Hi Geoff,\n\nThanks for reaching out with your questions.\n\nOur fees for sellers are typically a success-based percentage of the sale price, meaning we only get paid when your business successfully sells. We generally do not charge upfront fees, though specific arrangements can vary depending on the complexity of the engagement.\n\nThe typical engagement length can range from 6 to 12 months, from initial preparation through to settlement. This can vary based on market conditions, the specific nature of the business, and how quickly all parties can complete due diligence.\n\nIf you'd like to discuss a particular scenario, please feel free to provide a bit more detail, or we can organise a brief call to walk through our process.\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": []
  },
  "enq-009": {
    "classification": "general_question",
    "classification_confidence": 0.95,
    "classification_reasoning": "The enquiry is an attempt to override instructions, which is handled as an out-of-scope general question.",
    "urgency": "low",
    "geography": "unspecified",
    "route_to": "intake",
    "recommended_action": "Politely redirect the user, explaining this is a triage system for genuine business enquiries.",
    "suggested_reply": {
      "subject": "Regarding your enquiry",
      "body": "Hi there,\n\nThis is an automated triage system designed to process genuine enquiries for Strata Business Brokers. We specialise in the sale and purchase of strata management businesses.\n\nIf you have a legitimate business enquiry related to buying, selling, or valuing a strata management business, please resubmit with the relevant details.\n\nKind regards,\nThe Strata Business Brokers Team"
    },
    "flags": [
      "out_of_scope"
    ]
  }
};
