/**
 * One-shot script: runs each seeded enquiry through analyzeEnquiry()
 * and writes the resulting analyses to lib/seeded-analyses.ts.
 *
 * Run after editing the prompt or sample enquiries:
 *   npm run cache-seeds
 *
 * Cached analyses are committed so the dashboard renders instantly on
 * click for the seeded enquiries; only user-pasted enquiries hit Gemini
 * live. Documented in README "Why we pre-cache".
 */
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { sampleEnquiries } from "@/lib/sample-enquiries";
import { analyzeEnquiry } from "@/lib/gemini";

async function main(): Promise<void> {
  if (!process.env.GEMINI_API_KEY) {
    console.error("GEMINI_API_KEY is not set in .env.local. Aborting.");
    process.exit(1);
  }

  const cache: Record<string, unknown> = {};
  let failures = 0;
  // Free tier: 5 RPM on gemini-2.5-flash. Sleep 13s between calls to stay under.
  const THROTTLE_MS = 13_000;

  for (let i = 0; i < sampleEnquiries.length; i++) {
    const enq = sampleEnquiries[i];
    process.stdout.write(`  ${enq.id}  ${enq.subject.padEnd(50).slice(0, 50)} ... `);
    const result = await analyzeEnquiry(enq.body);
    if (result.ok) {
      cache[enq.id] = result.analysis;
      console.log(
        `OK  ${result.meta.latency_ms}ms  conf=${result.analysis.classification_confidence.toFixed(2)}  ${result.analysis.classification}  ${result.meta.self_corrected ? "[self-corrected]" : ""}`,
      );
    } else {
      failures++;
      console.log(`FAIL  ${result.error}: ${result.message.slice(0, 100)}`);
    }
    if (i < sampleEnquiries.length - 1) {
      await new Promise((r) => setTimeout(r, THROTTLE_MS));
    }
  }

  if (failures > 0) {
    console.error(`\n${failures} enquiries failed. Not writing cache.`);
    process.exit(1);
  }

  const out = `import type { Analysis } from "@/lib/schema";

/**
 * Pre-cached analyses for seeded enquiries.
 *
 * Generated by scripts/precache-seeds.ts. Re-run after editing the prompt
 * or sample enquiries: \`npm run cache-seeds\`.
 *
 * The dashboard renders these instantly on click; only user-pasted
 * enquiries hit Gemini live. Documented in README "Why we pre-cache".
 */
export const seededAnalyses: Record<string, Analysis> = ${JSON.stringify(cache, null, 2)};
`;

  const dest = path.resolve(process.cwd(), "lib/seeded-analyses.ts");
  await writeFile(dest, out, "utf8");
  console.log(`\nWrote ${Object.keys(cache).length} analyses to lib/seeded-analyses.ts`);
}

main().catch((err) => {
  console.error("Unhandled error:", err);
  process.exit(1);
});
